language: groovy
jdk:
  - oraclejdk8
script:
  - "./gradlew test"
before_cache:
  - rm -f "$HOME/.gradle/caches/modules-2/modules-2.lock"
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
before_deploy:
  - 'echo "gradle.publish.key=$GRADLE_PUBLISH_KEY" >> ~/.gradle/gradle.properties'
  - 'echo "gradle.publish.secret=$GRADLE_PUBLISH_SECRET" >> ~/.gradle/gradle.properties'
deploy:
  - provider: script
    script: ./gradlew publishPlugins
    on:
      tags: true
